### ISSUE TITLE
Data Value Sets Fetch API Support for Start and End Date Query Parameters

### ISSUE THREAD

**Issue by chaiwa-berian** [OpenFn/language-dhis2#12]
I am wondering whether the use of **startDate** and **endDate** query parameters are being supported by the **fetchData** API. I tried the below configuration and I am only getting an empty(`{}`) response:

```
fetchData({
  fields: {
    dataSet: 'MVccvKD4o8Q',
    orgUnit: 'Gmn6FKMQQ13',
    startDate: '2017-01-01',
    endDate: '2018-01-01'
  },
  postUrl: "https://www.openfn.org/inbox/id_for_my_inbox"
})
```

**Comment by chaiwa-berian** [comment]
Hi @taylordowns2000 , I tried to replicate the issue. Here are the few things I noticed:

1. The DHIS2 **/dataValueSets** endpoint may have been deprecated
- i.e. If you send an **api url** with **/api/{version}/dataValueSets**, the data gets fetched, where `{version}` is older.
- If you make a call on latest version of the DHIS2 api, i.e., by sending the **url** with **/api/dataValueSets** it doesn't work. It seems the **/api/dataValueSets** endpoint has been deprecated. It doesn't even seem to be available in the **api resources** via **https://play.dhis2.org/2.35.0/api/resources.json?skipPaging=true**
- Not conclusive, we may need to investigate

2. We need to investigate more why params are not being sent via **fecthData** of the DHIS2 language package: [docs](https://docs.dhis2.org/2.30/en/developer/html/dhis2_developer_manual_full.html#webapi_reading_data_values)

**Comment by taylordowns2000** [comment]
Closing this as it doesn't seem to be an issue anymore. `fetchData` is working as expected.
