### ISSUE TITLE
Does upsertTEI(...) work as specified?

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-dhis2#17]
Test this `upsertTEI(...)` helper on any DHIS2 instance, and I don't think this will work. Please try with the DHIS2 Play instance to verify... but I've never been able to get the `CREATE_AND_UPDATE` strategy to work. 
https://github.com/OpenFn/language-dhis2/blob/d250169406adfd4a1fe84e7a6ba1d04f3b3277b4/src/Adaptor.js#L337-L376

Also...
1. don't we need to specify the TEI `Id` somewhere in order to upsert?
2. Please update the readme docs to reflect all available helper functions 

In past DHIS2 projects we've had to implement a pattern where we first `GET` a TrackedEntity, and then `PUT` or `POST` to upsert depending on the `GET` search results - see here: https://github.com/OpenFn/logical-outcomes/blob/master/tnc/CSVtoDHIS2__http.js

**Comment by aleksa-krolls** [comment]
@taylordowns2000 assigning to you because not sure who originally wrote this function. 

cc @chaiwa-berian fyi, i don't this this `upsertTEI(...)` function will work until this issue is resolved.

**Comment by taylordowns2000** [comment]
@chaiwa-berian see the attached image of documentation on https://docs.dhis2.org/2.26/en/developer/html/webapi_tracked_entity_instance_management.html#webapi_creating_tei : 

Could you confirm whether or not this API documentation is valid? We need to know:
1. does `upsertTEI` in OpenFn's `language-dhis2` match the api specification above?
2. does the API specification _actually_ work on the demo DHIS2 instance?

 ![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/280d1b28-d933-4874-b77f-637863a93c80)

**Comment by aleksa-krolls** [comment]
@chaiwa-berian As discussed, I think we will need 2 upsert functions (or at least an option to specify a custom uid)...

1. If using the DHIS2-generated Id (e.g., `h3F1leJ0buf`) to update tracked entities, then I think we can `POST` using `strategy=CREATE_AND_UPDATE` --> please test to confirm this works. 
2. However, if using a custom unique identifier (e.g., the attribute `aX5hD4qUpRW`), then we need to first `GET` searching existing TEIs by this custom Id... and then we can either `PUT` (for updates) or `POST` (to create new). See logical-outcomes job here: https://github.com/OpenFn/logical-outcomes/blob/master/demo/upsertTrackedEntity.js#L66

Then, there is the question you raised re: enrollments and whether we are able to update existing enrollments. I recommend testing `enrollment` updates for both scenarios above. Also consider if we still need to add on `strategy=CREATE_AND_UPDATE` to any [`PUT` requests](https://github.com/OpenFn/logical-outcomes/blob/master/demo/upsertTrackedEntity.js#L68) to ensure we update the enrollments (and not create new ones). 

We might need to ask the DHIS2 community to explain how enrollments work and whether multiple enrollments are allowed for the same program, because currently I only see 1 `enrollment` on the front-end for [this TEI](https://training.logicaloutcomes.net/dhis-web-tracker-capture/index.html#/dashboard?tei=h3F1leJ0buf&program=wZLN40noez1&ou=w1JagOAiHcM), even though you see multiple `enrollment` records in the back-end. 

cc @taylordowns2000
