### ISSUE TITLE
Generic helpers for new composed functions

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-dhis2#22]
The full list of functionality is in @chaiwa-berian 's comment below.

**Comment by taylordowns2000** [comment]
Hey @chaiwa-berian , I've looked through your current work and I like the concept of providing `update`, `upsert` etc., as named functions, but please rename `post` to `create`. The function should use the CRUD verb and `axios` itself refernce the method.

Also, I see this:
```js
        const nextState = {
          ...state,
          data: result?.data,
          references: [...state?.references, result?.data],
        };
```
repeated throughout. can you make use of `composeNextState` from `language-common`?

**Comment by chaiwa-berian** [comment]
# Progress Update - Testing
- The **great news** is that the **generic upsert passes ALL the tests.** :heart_eyes:
- The rest of the opertaions have not yet been tested, except **getData**  which has also passed all the tests.
## Commonly Used Helper Operations
- [ ] getTEIs
- [ ]  upsertTEI
- [ ] createTEI
- [ ] updateTEI
- [ ] getEvents
- [ ] createEvents
- [ ] updateEvents
- [ ] getPrograms
- [ ] createPrograms
- [ ] updatePrograms
- [ ] getEnrollments
- [ ] createEnrollment
- [ ] updateEnrollments
- [ ] cancelEnrollment
- [ ] completeEnrollment
- [ ] getRelationships
- [ ] getDataValues
- [ ] createDataValues

## GENERIC HELPER OPERATIONS
- [ ] generateDhis2UID
- [ ] discover
- [ ] getAnalytics
- [ ] getResources
- [ ] getSchema
- [x] getData
- [ ] getMetadata
- [ ] create
- [ ] update
- [ ] patch
- [ ] del
- [x] upsert

**Comment by chaiwa-berian** [comment]
@taylordowns2000 Fixed a few bugs via tests, written tests for each generic operation(4 remaining), and  updated docs for  generic helper operations(4 remaining). First 2-3 hours in the morning should allow me to finish writing tests for the generic helper functions.

I may still have to write tests for the commonly used helper functions, too. This would give me confidence of their correctness and also example expressions to add to the `jsdocs`. So I would say, I may still take tomorrow for the final touches.

The `recursivelyExpandReferences` function has been refactored to account for a few more scenarios that I encountered during testing. We can review it together tomorrow. Thanks.

**Comment by taylordowns2000** [comment]
for today's testing:
- [ ] getDataValues
- [ ] createDataValues
- [ ] createEvents
- [ ] createEnrollments

**Comment by chaiwa-berian** [comment]
@taylordowns2000 I am done writing the assigned tests but for some reason all calls to the `Tracker Web API endpoints` are failing. I.e. all calls to deal with TEIs, **events**, **enrollments** or **programs** are suddenly failing. I am breaking off but I might need to investigate this further next week.

**Comment by taylordowns2000** [comment]
Understood—I'm sure it has to do with config changes on play. Each night
those instances are re-deployed. I'll be surprised if it doesn't work on
Monday :-)
