### ISSUE TITLE
Update inline docs for platform usage

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-dhis2#29]
The jsDocs for version `2.0.0` are extensive, going well beyond those provided in `v1.4.0`. This is great :partying_face: but we've got to ensure that they still can be used to generate inline documentation for folks who are using this adaptor on the openfn.org platform.

**Please update the inline docs here so that an [ast can be generated](https://github.com/openfn/simple-ast#cli-usage) from this adaptor before we build and link a new tarball to the `2.0.0` release.**

You can check for a valid ast (as would be done during the build process for OpenFn.org) with this command, executed in the `simple-ast` root directory:  `node ./lib/generate.js --adaptor ~/devtools/adaptors/language-dhis2/lib/Adaptor.js --output ./tmp/ast.json`

**N.B., If you feel that the current documentation is accurate and _should_ be producing a valid AST, please feel free to propose changes to https://github.com/OpenFn/simple-ast/blob/master/lib/generate.js so that it handles this new style of documentation as well as the older method in use across the adaptors. `generate.js` is, admittedly, _very brittle_ because we'd always done inline documentation for adaptors in a very particular way.**

**Comment by chaiwa-berian** [comment]
@taylordowns2000 I need a little bit more clarity here. Is the task related to this [branch](https://github.com/OpenFn/language-dhis2/tree/read_metadata_return_as_json) ? Are you asking me to debug the jsdocs in this branch until they build successfully? Thanks

**Comment by taylordowns2000** [comment]
I know we spoke on slack, but for the record:

Please branch off 'master'.

The objective is to get simple-ast to produce an ast from the code so that
we can use that ast when we deploy this new version to OpenFn.org
