### ISSUE TITLE
Rename functions with singular names rather than plural names

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-dhis2#38]
Do these functions actually take an array _or_ and object? If not, they should probably be renamed:

1. `createPrograms` should be `createProgram`
2. `createEvents` should be `createEvent`
3. ...more?

If so, can we add some explanation in the docs which shows that these functions take objects or arrays? ( To consider, @chaiwa-berian , I know that there was some issue around how JsDoc parses these optional args.)

**Comment by elias-ba** [comment]
Great @taylordowns2000, adding that to my plate.
