### ISSUE TITLE
Test coverage for new functions

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-dhis2#44]
In addition to the existing tests, please extend the tests on @elias-ba 's branch to cover:

## create
- [x] create makes a POST
- [x] the proper URL gets built from the 'entity' string and the config
- [x] when an array is passed it gets nested inside that "entity" key
- [x] when an object is passed it doesn't get nested
- [x] when an object, an array, OR a function, it gets properly "expanded" with expandReferences
- [x] the proper authentication gets built

## update
- [x] update makes a PUT
- [x] the proper URL gets built from the 'entity' string and the config
- [x] when an array is passed it gets nested inside that "entity" key
- [x] when an object is passed it doesn't get nested
- [x] when an object, an array, OR a function, it gets properly "expanded" with expandReferences
- [x] the proper authentication gets built

and keep your eyes sharp for "features" of the helper functions that are not yet in this list.

**Comment by lakhassane** [comment]
Temporary feedback on this

1. `update` does not take array, so proly no need to write test for `checkboxes 3 and 4`
2. ` the proper URL gets built from the 'entity' string and the config` this is more related to the functionality of `buildUrl` and not `update`/`create`. So should test that function separately (in the same file still).
3. ...
