### ISSUE TITLE
Upsert or "import strategy: create and update"

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-dhis2#48]
It's not clear to me whether `importStrategy: 'CREATE_AND_UPDATE'` is available for common resourceTypes like `trackedEntityInstances`. I see it mentioned [here](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-235/web-api.html#webapi_metadata_create_update) and in a few more places, but does DHIS2 actually support upserts?

If not, I'd like to see a composed `upsert` that either attempts to create and then updates on conflict, or attempts to get and then either creates or updates depending on whether the get succeeds.

While we've used the `get` then `post` or `put` method for other adaptors, given that the required parameters can change between `get` and `create` for dhis2 (`ou` to `orgUnit` seemingly) I'm starting to think we should attempt to create and catch the error, updating if we get a conflict. We just need to make sure that we get back the canonical ID when the create fails due to a conflicting external ID.

If I try to create a TEI twice with the same data:
```js
create('trackedEntityInstances', {
  orgUnit: 'DiszpKrYNg8',
  trackedEntityType: 'Zy2SEgA61ys',
  attributes: [
    {
      attribute: 'flGbXLXCrEo', // system case ID
      value: '123',
    },
  ],
});
```
The first attempt succeeds and then I get this `409` on the second. Could we use that to then send an update? Doubtful, as it lacks the TEI id:
```
✗ Error at Tue Dec 21 2021 22:22:20 GMT-0700 (Mountain Standard Time):
 Request failed with status code 409
{
  "responseType": "ImportSummaries",
  "status": "ERROR",
  "imported": 0,
  "updated": 0,
  "deleted": 0,
  "ignored": 1,
  "importOptions": {
    "idSchemes": {},
    "dryRun": false,
    "async": false,
    "importStrategy": "CREATE_AND_UPDATE",
    "mergeMode": "REPLACE",
    "reportMode": "FULL",
    "skipExistingCheck": false,
    "sharing": false,
    "skipNotifications": false,
    "skipAudit": false,
    "datasetAllowsPeriods": false,
    "strictPeriods": false,
    "strictDataElements": false,
    "strictCategoryOptionCombos": false,
    "strictAttributeOptionCombos": false,
    "strictOrganisationUnits": false,
    "requireCategoryOptionCombo": false,
    "requireAttributeOptionCombo": false,
    "skipPatternValidation": false,
    "ignoreEmptyCollection": false,
    "force": false,
    "firstRowIsHeader": true,
    "skipLastUpdated": true,
    "mergeDataValues": false,
    "skipCache": false
  },
  "importSummaries": [
    {
      "responseType": "ImportSummary",
      "status": "ERROR",
      "importOptions": {
        ...blah
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        ...blah
      },
      "importCount": {
        "imported": 0,
        "updated": 0,
        "ignored": 1,
        "deleted": 0
      },
      "conflicts": [
        {
          "object": "Attribute.value",
          "value": "Non-unique attribute value 'ZRP792320' for attribute flGbXLXCrEo"
        }
      ],
      "enrollments": {
        "responseType": "ImportSummaries",
        "status": "SUCCESS",
        "imported": 0,
        "updated": 0,
        "deleted": 0,
        "ignored": 0,
        "importSummaries": [],
        "total": 0
      }
    }
  ],
  "total": 1
}
```
But maybe we could then perform a `get` which looks for just TEIs with that attribute/value combination, grab the ID, and then update? Using the following I can snag the dhis2 id:
```js
get('trackedEntityInstances', {
  ou: 'DiszpKrYNg8',
  filters: ['flGbXLXCrEo:Eq:123'],
});
```

**Comment by taylordowns2000** [comment]
In the end, it feels like we should have an `upsert` function with the following signature:
```js
upsert(resourceType, uniqueFilter, data, options, callback)
``` 
where `uniqueFilter` must be a something like `{ flGbXLXCrEo: 123 }`, given the example above where `flGbXLXCrEo` is the attribute ID of a "system case ID" in a dhis2 instance

**Comment by elias-ba** [comment]
@taylordowns2000 I am a little bit confused by this issue. What's the main problem you're raising here ? Why should we go from upsert being `get then create if no result update otherwise` to `create then update if error` ? Could you give me more clarifications on this when you come online ?

**Comment by taylordowns2000** [comment]
No, given the response (above) to the failed create it looks like we've got to stick with `get-then-create/update`. Unless you've got strong opinions otherwise, I think we should go with the pattern laid out here: https://github.com/OpenFn/language-dhis2/issues/48#issuecomment-999318629

I'm not certain that it's possible to make this work across different resource types, so it's possible that the `uniqueFilter` argument needs to actually be a full `query` argument from `get(resourceType, query)`. If that were the case, the signature would be: `upsert(resourceType, query, data, options, callback)` and it would:

1. run a get with the query
2. fail if it gets more than one resource
3. perform a create if it gets 0 resources
4. perform an update with the path returned (somehow using the response to identify the dhis2 `id`) if it gets 1 resource

**Comment by elias-ba** [comment]
Okay awesome, what's the remaining work to do there ? In your changes did you implement this already ?
